openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1
tags:
  - name: opts
    description: 運用監視関連のAPI
  - name: auth
    description: 認証関連のAPI
  - name: tasks
    description: タスク関連のAPI
paths:
  /health:
    get:
      tags:
        - opts
      responses:
        '200':
          description: OK
  /token:
    post:
      summary: "JWTトークンを取得"
      description: "ユーザーのBasic認証情報を使用してJWTトークンを取得します。"
      operationId: "generateToken"
      tags:
        - auth
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: "JWTトークンの発行に成功しました"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: "発行されたJWTトークン"
  /tasks/:
    get:
      summary: "タスク一覧取得"
      description: "タスクの一覧を取得できます"
      operationId: "GetTasks"
      security:
        - Bearer: []
      tags:
        - tasks
      parameters:
        - name: limit
          in: query
          required: true
          description: "リストに含まれるリソースの最大値"
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 10
        - name: offset
          in: query
          required: true
          description: "オフセット"
          schema:
            type: integer
            format: int64
            minimum: 0
            default: 0
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskListDTO"
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
    post:
      summary: "タスク作成"
      description: "タスクを新規作成します"
      operationId: "createTask"
      security:
        - Bearer: []
      tags:
        - tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskForm"
      responses:
        201:
          description: "Created"
          headers:
            location:
              description: "作成されたリソースのURI"
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDTO"
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
  /tasks/{taskId}:
    get:
      summary: "タスク取得"
      description: "指定されたIDのタスクを1件取得します"
      tags:
        - tasks
      operationId: "GetTask"
      security:
        - Bearer: []
      parameters:
        - name: taskId
          in: path
          required: true
          description: "詳細を取得するタスクのID"
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDTO"
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceNotFoundError"
    put:
      summary: "タスク更新"
      description: "指定されたタスクをリクエストボディの内容で上書きします"
      operationId: "EditTask"
      security:
        - Bearer: []
      tags:
        - tasks
      parameters:
        - name: taskId
          in: path
          required: true
          description: "更新するタスクのID"
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskForm"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDTO"
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceNotFoundError"
    delete:
      summary: "タスク削除"
      description: "指定されたタスクを削除します"
      operationId: "DeleteTask"
      security:
        - Bearer: []
      tags:
        - tasks
      parameters:
        - name: taskId
          in: path
          required: true
          description: "更新するタスクのID"
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: "No Content"
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        '404':
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceNotFoundError"
components:
  schemas:
    TaskForm:
      type: object
      properties:
        title:
          type: string
          description: "作成されるタスクのタイトル"
          maxLength: 256
          minLength: 1
        status:
          type: string
          enum: ["inProgress", "done"]
          description: "タスクのステータス"
      required:
        - title
    TaskDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: "タスクID"
        title:
          type: string
          description: "タスクのタイトル"
        status:
          type: string
          enum: ["inProgress", "done"]
          description: "タスクのステータス"
      required:
        - id
        - title
    PageDTO:
      description: "ページング情報"
      type: object
      properties:
        limit:
          description: "リクエストされた limit"
          type: integer
          format: int32
        offset:
          description: "リクエストされた offset"
          type: integer
          format: int64
        size:
          description: "取得できた件数"
          type: integer
          format: int32
      required:
        - limit
        - offset
        - size
    TaskListDTO:
      description: "タスクのリスト"
      type: object
      properties:
        page:
          $ref: "#/components/schemas/PageDTO"
        results:
          type: array
          items:
            $ref: "#/components/schemas/TaskDTO"
      required:
        - results
    UnauthorizedError:
      description: "認証に失敗しました"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Unauthorized"
        detail:
          type: string
          description: "エラーの詳細"
      required:
        - title
        - detail
    ResourceNotFoundError:
      description: "指定したリソースが存在しない"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Resource Not Found"
        detail:
          type: string
          description: "エラーの詳細"
      required:
        - title
        - detail
    BadRequestError:
      description: "リクエストが不正"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
          default: "Bad Request"
        detail:
          type: string
          description: "エラーの詳細"
          default: "リクエストが不正です。正しいリクエストでリトライしてください"
        invalid-params:
          type: array
          items:
            $ref: "#/components/schemas/InvalidParam"
      required:
        - title
        - detail
        - invalid-params
    InvalidParam:
      description: "不正なリクエストについての詳細"
      type: object
      properties:
        name:
          type: string
          description: "エラーが発生したフィールド名"
        reason:
          type: string
          description: "エラーの理由"
      required:
        - name
        - reason
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "jwt認証token"
