spring:
  application:
    name: todo
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/sql/schema.sql
#      初期化したくないため無効
#      data-locations: classpath:/sql/data.sql
mybatis:
  type-handlers-package: com.rujuu.todo.handler
server:
  port: 8081

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
